name: "Godot Manual Export All"
on: [push, workflow_dispatch]

jobs:
  export:
    name: Export All Platforms
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Generate Android Keystore
        id: keystore
        run: |
          keytool -keyalg RSA -genkeypair -alias androiddebugkey -keypass android -keystore debug.keystore -storepass android -dname "CN=Android Debug,O=Android,C=US" -validity 9999
          echo "keystore_b64=$(base64 -w 0 debug.keystore)" >> $GITHUB_OUTPUT

      - name: Godot Export
        id: export
        uses: firebelley/godot-export@v5.2.1
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.2.1/Godot_v4.2.1-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.2.1/Godot_v4.2.1-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true
          android_keystore_base64: ${{ steps.keystore.outputs.keystore_b64 }}
          android_keystore_alias: androiddebugkey
          android_keystore_password: android
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: LiarsBar-Builds
          path: ${{ steps.export.outputs.build_directory }}/*
